baseurl = "http://jhyoon0801.github.io/blog"
languageCode = "us-en"
title = "Welcome to jhyoon's blogs"
copyright = "Copyright &#169; by jhyoon"
canonifyurls = true
publishdir = "public"
contentdir = "content"
theme = "grid-side"
SectionPagesMenu = "Main"

[Params.Header]
    name = "jhyoon"
    description = "server programmer"
    email = "jhyoon0801@gmail.com"
    image = "/img/background.jpg"

 [[Params.Cells.List]]
            name = "Blogs"
            link = "http://jhyoon0801.github.io/blog/blogs/"
            color = "blue"
